services:
  mariadb-archive:
    image: mariadb:10.11
    container_name: mariadb-archive
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: photoroot
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: photopass
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /svc/docker/mariadb-archive:/var/lib/mysql-archive

  photoprism-archive:
    image: photoprism/photoprism:latest
    container_name: photoprism-archive
    depends_on:
      mariadb-archive:
        condition: service_healthy
    ports:
      - "2343:2342"
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}
      PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
      PHOTOPRISM_STORAGE_PATH: /photoprism/storage
      PHOTOPRISM_IMPORT_PATH: /photoprism/import
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb-archive:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "photopass"
      PHOTOPRISM_SITE_TITLE: "Fototresor"
      PHOTOPRISM_SITE_CAPTION: "Hier ist der Schatz"
    volumes:
      - /mnt/raid/lichtkasten/archive/originals:/photoprism/originals
      #- /mnt/raid/lichtkasten/archive/import:/photoprism/import
      - ./test-fotos:/photoprism/import
      - /svc/docker/photoprism-archive/storage:/photoprism/storage
    restart: unless-stopped

